name: zabbix_alert_rule
pack: get_zabbix_msg
description: Rule to process Zabbix alert messages
enabled: true
trigger:
  type: zabbix.event_handler
action:
  ref: get_zabbix_msg.msg_st2
  parameters:
    alert_message: "{{ payload.alert_message }}"

